//! - CHECAR QUE CUANDO FILTRES POR NOMBRE Y TE APAREZCA LA CARD DEL CORREDORR, PARA 
//!   REGRESAR A HOME PRESIONAR UN BOTON QUE VUELVA A RENDERIZAR TODAS LAS CARDS.

//! - REMOVER EL HOME Y CAMBIARLO POR IMAGEN (NAVBAR)

//! - NUMERO DEL PAGINADO 1, 2, 3, 4 ...